// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgToD-tMDEtrj38p5RATHgmwir60TNB0',
    appId: '1:844681387063:web:f5b9d1d5f96a9d3a8733b2',
    messagingSenderId: '844681387063',
    projectId: 'job-task-3b02c',
    authDomain: 'job-task-3b02c.firebaseapp.com',
    storageBucket: 'job-task-3b02c.firebasestorage.app',
    measurementId: 'G-XGBMPLFFD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq8JhcabsJiNbHr2f8bEwJ04l9SVV0ki8',
    appId: '1:844681387063:android:e0c1561fa01f74618733b2',
    messagingSenderId: '844681387063',
    projectId: 'job-task-3b02c',
    storageBucket: 'job-task-3b02c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsKkvPoGJfz38V32LnaFsxXEFyD-oNEUc',
    appId: '1:844681387063:ios:d9c84e85f871fc198733b2',
    messagingSenderId: '844681387063',
    projectId: 'job-task-3b02c',
    storageBucket: 'job-task-3b02c.firebasestorage.app',
    iosBundleId: 'com.example.shahinTask',
  );
}
